version: '3'
services:
  blog:
    image: nginx:latest
    container_name: blog
    ports:
      - 7700:80
    volumes:
      - ./docs/.vuepress/dist/:/usr/share/nginx/html/
    networks:
      - docker_default
    restart: unless-stopped
networks:
  docker_default:
    name: docker_default
    external: true
